export const tasks_ = [
  {
    description:"task - 01",
    status:"Ongoing",
    type:"Contract",
    strategy:"Tendering",
    rfqRef:"",
    access:"A",
    departement:"Engineering",
    internalClient:"Vikesh",
    statusDetails:"Revision of T&C",
    receivedOffer:"",
    nextAction:"Reply Fluor Comments by legal",
    who:"Diary",
    sowSrfReceived:"",
    frqSent:"",
    siteVisit:"",
    frqClosed:"",
    extendedClosingDate:"",
    quotationSentToEu:"",
    quoteClarif:"",
    tbe:"",
    cbe:"",
    rtaSub:"",
    rtaValid:"",
    execDate:"",
    budget:"",
    saving:"",
    nextStep:"",
    bidders:"DRA_FLUOR_SNC"
  }
]