export const tasks = [
  {
    id: '0001',
    name: 'Contract-1',
    startDate: new Date('12-02-2021'),
    endDate: new Date('01-01-2022'),
    responsible: 'John',
    statusDetail: 'status Detail',
    status: 'Working on it',
  },
  {
    id: '0002',
    name: 'Contract-2',
    startDate: new Date('01-01-2022'),
    endDate: new Date('02-01-2022 01:00:00'),
    responsible: 'Hasimanitra',
    statusDetail: 'status Detail',
    status: 'Stuck',
  },
  {
    id: '0003',
    name: 'Contract-3',
    startDate: new Date('02-01-2022 11:43:22'),
    endDate: new Date('03-01-2022'),
    responsible: 'Liantso',
    statusDetail: 'status Detail',
    status: 'Done',
  },
  {
    id: '0004',
    name: 'Contract-4',
    startDate: new Date('03-01-2022 02:14:41'),
    endDate: new Date('03-10-2022'),
    responsible: 'Lanto',
    statusDetail: 'status Detail',
    status: 'Working on it',
  },{
    id: '0005',
    name: 'Contract-5',
    startDate: new Date('03-01-2022 02:14:41'),
    endDate: new Date('03-10-2022'),
    responsible:'Haja',
    statusDetail: 'status Detail',
    status: 'Working on it',

    // Diary TAF
    sourcingDescription:'MSA FLUOR',
    receivedOffer:'',
    nextAction:'',
    who:'Diary',
    sowSrfReceived:'',
    frqSent:'',
    siteVisit:'',
    frqClosed:'',
    extendedClosingDate:'',
    quotationSentToEu:'',
    quoteClarif:'',
    tbe:'',
    cbe:'',
    rtaSub:'',
    rtaValid:'',
    execDate:'',
    budget:'',
    saving:'',
    bidders:'',
  }
]